### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Wang-Shengyuan** [zwq2018/Multi-modal-Self-instruct#2]
Thank you for your research and open-source work!

I noticed a typo in the Multi-modal-Self-instruct/README.md file, specifically in the following section:

- Abstract Image Generation

   - Domain generation: The file name `bootstrap_domains.py` is misspelled as `boostrap_domains.py`.

See #1 please.

**Comment by zwq2018** [comment]
ok thk. I merge the PR
