### ISSUE TITLE
Release code that renders the images

### ISSUE THREAD

**Issue by xfgao** [zwq2018/Multi-modal-Self-instruct#4]
Hi, thanks for the great work. 

If I understand correctly, each image in the dataset is generated by some python code. Would it be possible to provide the code that renders the images? Thanks!

**Comment by zwq2018** [comment]
> Hi, thanks for the great work.
> 
> If I understand correctly, each image in the dataset is generated by some python code. Would it be possible to provide the code that renders the images? Thanks!

Hello, thank you for your attention.   

In our codebase, we have provided a complete pipeline for generating visual ideas, code, and final images.

**Comment by xfgao** [comment]
I see. 

Generating new data through the pipeline can be costly and takes some extra effort. Would it be possible to directly provide the code that renders existing images in the huggingface [repository](https://huggingface.co/datasets/zwq2018/Multi-modal-Self-instruct)?

**Comment by zwq2018** [comment]
> I see.
> 
> Generating new data through the pipeline can be costly and takes some extra effort. Would it be possible to directly provide the code that renders existing images in the huggingface [repository](https://huggingface.co/datasets/zwq2018/Multi-modal-Self-instruct)?

ok, I understand what you mean. I have to look for those codes generated by LLM.

**Comment by zwq2018** [comment]
> I see.
> 
> Generating new data through the pipeline can be costly and takes some extra effort. Would it be possible to directly provide the code that renders existing images in the huggingface [repository](https://huggingface.co/datasets/zwq2018/Multi-modal-Self-instruct)?

We have uploaded most of the synthetic code in `original_dataset.zip`. However, some datasets may be incomplete.

**Comment by xfgao** [comment]
Thanks!
